name: Node

on:
  push:
    branches: ["main", "dev-*"]
  pull_request:
    branches: ["main", "dev-*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm install --no-package-lock
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test
      - run: npm run build
      - run: npx --yes publint@0.3 run
      - run: npx --yes @arethetypeswrong/cli@0.18 --pack
      - run: npm pack --dry-run
